### ISSUE TITLE
problem with building bwt inorder to run ebwt2indel

### ISSUE THREAD

**Issue by Kedraous** [nicolaprezza/ebwt2snp-v2#2]
Hello,

I'm trying to use ebwt2InDel to find SNPs in sequencing reads. I'm using the following code to build bwt of my paired end reads.

BCR\_LCP\_GSA 9_S6_L004_R1_001.fastq.gz 9_S6_R1.fastq.bwt 
BCR\_LCP\_GSA 9_S6_L004_R2_001.fastq.gz) 9_S6_R2.fastq.bwt 

I have removed the reads containing N prior to running the job. However, I kept getting an error indicating "The  (new and-or old) reads have a different length".  And following that, I processed the reads with fastp to make all the reads of equal length, but I'm still getting the same error. I also tried including zcat to unpack the reads, but the same error. 

The error;

TIMER start buildBCR User: 3e-06s System: 1.1e-05s Actual: 1.6e-05s Efficiency: 87.5%
The  (new and-or old) reads have a different length.
BCR_LCP_GSA: TransposeFasta.cpp:235: bool TransposeFasta::findLengthNseq(const string&, const string&, std::__cxx11::string): Assertion `lengthSeqVector.size() == nSeq' failed.
/var/spool/torque/mom_priv/jobs/29994642.moab.SC: line 15: 38504 Aborted                 (core dumped) BCR\_LCP\_GSA <(zcat 9_S6_L004_R1_001_no_N_151.fastq.gz) 9_S6_R1.fastq.bwt

Please help in clarifying if there is something I'm doing wrong 

Best regards,
Kedra

**Comment by nicolaprezza** [comment]
Hello! This is an error of BCR_LCP_GSA, so you should open the issue there: https://github.com/giovannarosone/BCR_LCP_GSA

Best 
Nicola
